string EntryName

#these are array fields the first
#array that is not zero length defines the datatype 
#of the menu entry
#the first value of it the value of the entry
#any other value or array comming later is IGNORED!

float64[] double_var
float32[] float_var
bool[]    boolean_var
int8[]    integer8_var
uint8[]   uinteger8_var
int16[]   integer16_var
uint16[]  uinteger16_var
int32[]   integer32_var
uint32[]  uinteger32_var
int64[]   integer64_var
uint64[]  uinteger64_var
